//! Generate regex patterns for matching emoji.

use crate::model::emoji::EmojiMap;
use std::path::Path;

/// Generate a regex pattern string that matches all emoji in the map.
///
/// This produces a character-class based regex. For full optimization
/// (trie-based compression like `regexgen`), a more sophisticated
/// algorithm would be needed.
pub fn generate_emoji_regex(emoji_map: &EmojiMap) -> String {
    let mut codepoints: Vec<u32> = emoji_map
        .keys()
        .filter_map(|hex| {
            // Only single-codepoint emoji for the character class.
            if hex.contains('-') {
                None
            } else {
                u32::from_str_radix(hex, 16).ok()
            }
        })
        .collect();

    codepoints.sort();
    codepoints.dedup();

    if codepoints.is_empty() {
        return String::new();
    }

    // Build character class ranges.
    let mut parts: Vec<String> = Vec::new();
    let mut i = 0;

    while i < codepoints.len() {
        let start = codepoints[i];
        let mut end = start;

        while i + 1 < codepoints.len() && codepoints[i + 1] == end + 1 {
            end = codepoints[i + 1];
            i += 1;
        }

        if start == end {
            parts.push(format!("\\u{{{:X}}}", start));
        } else if end - start == 1 {
            parts.push(format!("\\u{{{:X}}}\\u{{{:X}}}", start, end));
        } else {
            parts.push(format!("\\u{{{:X}}}-\\u{{{:X}}}", start, end));
        }

        i += 1;
    }

    format!("[{}]", parts.join(""))
}

/// Generate regex patterns for multi-codepoint sequences (ZWJ, flags, etc.).
pub fn generate_sequence_regex(emoji_map: &EmojiMap) -> Vec<String> {
    let mut sequences: Vec<String> = emoji_map
        .keys()
        .filter(|hex| hex.contains('-'))
        .cloned()
        .collect();

    // Sort by length descending so longer sequences match first.
    sequences.sort_by(|a, b| b.len().cmp(&a.len()));

    sequences
        .into_iter()
        .map(|hex| {
            hex.split('-')
                .map(|part| format!("\\u{{{part}}}"))
                .collect::<Vec<_>>()
                .join("")
        })
        .collect()
}

/// Write regex patterns to JavaScript files.
pub fn write_regex_files(
    emoji_map: &EmojiMap,
    output_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    std::fs::create_dir_all(output_dir)?;

    let char_class = generate_emoji_regex(emoji_map);
    let sequences = generate_sequence_regex(emoji_map);

    // Build the full pattern.
    let mut pattern_parts = sequences;
    if !char_class.is_empty() {
        pattern_parts.push(char_class);
    }

    let full_pattern = pattern_parts.join("|");

    // emoji.js
    let emoji_js = format!(
        "// AUTO-GENERATED by emojibase-generator\nexport default /(?:{})/g;\n",
        full_pattern
    );
    std::fs::write(output_dir.join("emoji.js"), &emoji_js)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_emoji_regex() {
        let mut map = EmojiMap::new();
        map.insert("1F600".to_string(), crate::model::emoji::GeneratorEmoji {
            description: "grinning face".to_string(),
            hexcode: "1F600".to_string(),
            property: vec![],
            presentation: emojibase_core::types::Presentation::Emoji,
            unicode_version: None,
            version: "1.0".to_string(),
            gender: None,
            group: 0,
            order: 1,
            subgroup: 0,
            name: "".to_string(),
            modifications: None,
            qualifiers: None,
            variations: None,
            shortcodes: None,
            emoticon: None,
        });
        let regex = generate_emoji_regex(&map);
        assert!(regex.contains("1F600"));
    }
}
